name: Ubuntu20.04, ROS2 Continuous Integration

on:
  push:
    branches:
    - mnaveau/ros2
    - master
    - devel
  pull_request:
    branches:
    - master
    - devel

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      #
      # Setup the machines and build environment
      #
      - name: Install ROS.
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: foxy

      #
      # Checkout the current branch
      #
      - uses: actions/checkout@v2

      #
      # Run the generator and output the results to a file.
      #
      - name: Generate dependencies file.
        run: |
          rosinstall_generator dynamic_graph_bridge_msgs --rosdistro foxy \
          --deps-only --deps --upstream-development > /tmp/deps.repos

      #
      # Build and test the repo
      #
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: dynamic_graph_bridge_msgs
          target-ros2-distro: foxy
          vcs-repo-file-url: /tmp/deps.repos
